### ISSUE TITLE
Do our own gas accounting

### ISSUE THREAD

**Issue by lalexgap** [statechannels/SAFE-protocol#51]
I estimate probably 0.5 to 1 dev day to get our own gas accounting set up, following what we did [here](https://github.com/statechannels/statechannels/tree/master/packages/nitro-protocol/gas-benchmarks). I think it would be well worth the effort.

We could reuse quite a bit of the code that [we already wrote](https://github.com/statechannels/statechannels/blob/55ab6fd28ab1bade93a7d9648b25a8b63bd9dd55/packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts#L69).

_Originally posted by @geoknee in https://github.com/statechannels/SAFE-protocol/issues/11#issuecomment-984504723_

**Comment by lalexgap** [comment]
I think previous work relied on using `TransactionRequest` and `TransactionResponse` which looks like slightly different then using an ethers contract object. Hopefully we can do the same using an ethers `Contract`? Or maybe we should just switch to  using a `TransactionRequest` and `TransactionResponse`

**Comment by geoknee** [comment]
The previous work does use an ethers `Contract` instance, it just passes the return value (which is a `TransactionResponse`) into a helper function:

https://github.com/statechannels/statechannels/blob/55ab6fd28ab1bade93a7d9648b25a8b63bd9dd55/packages/nitro-protocol/gas-benchmarks/benchmark.test.ts#L67-L68

**Comment by lalexgap** [comment]
Ah good point, I missed that `ContractResponse` extends `TransactionResponse`
